name: CI

on:
  push:
    branches: [ master ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: unit test
        run: npm run test:unit
